const PAGE_FIVE = 5;
const PAGE_TEN = 10;
const PAGE_TWENTY_FIVE = 25;
const PAGE_FIFTY = 50;
const PAGE_ONE_HUNDRED = 100;

export const COUNT_PAGES = [
  PAGE_FIVE,
  PAGE_TEN,
  PAGE_TWENTY_FIVE,
  PAGE_FIFTY,
  PAGE_ONE_HUNDRED,
];
